cmap-timesheet-system/Models/ErrorViewModel.cs
namespace cmap_timesheet_system.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

cmap-timesheet-system/Models/TimesheetEntry.cs
namespace cmap_timesheet_system.Models
{
    public class TimesheetEntry
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public DateTime Date { get; set; }
        public string ProjectName { get; set; }
        public string TaskDescription { get; set; }
        public int HoursWorked { get; set; }

    }
}

cmap-timesheet-system/Controllers/HomeController.cs
using cmap_timesheet_system.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace cmap_timesheet_system.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

cmap-timesheet-system/Controllers/TimesheetController.cs
using cmap_timesheet_system.Models;
using cmap_timesheet_system.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace cmap_timesheet_system.Controllers
{
    public class TimesheetController : Controller
    {
        private readonly ITimesheetService _service;
        public TimesheetController(ITimesheetService service)
        {
            _service = service;    
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddEntry(TimesheetEntry entry)
        {
            _service.AddEntry(entry);
            return RedirectToAction("Index");
        }
    }
}

cmap-timesheet-system/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

cmap-timesheet-system/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cmap_timesheet_system</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cmap_timesheet_system.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cmap_timesheet_system</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Timesheet" asp-action="Index">Timesheet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - cmap_timesheet_system - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

cmap-timesheet-system/Views/Timesheet/Index.cshtml
@model TimesheetEntry
@{
    ViewData["Title"] = "Timesheet Entry";
}

<div class="text-left">
    <h1 class="display-4">Timesheet Entry</h1>

    <form asp-controller="Timesheet" asp-action="AddEntry" method="post">
        <div asp-validation-summary="ModelOnly"></div>

        <label>Username: <input asp-for="UserName" /></label> <br />
        <span asp-validation-for="UserName"></span><br />
        
        <label>Date: <input asp-for="Date" /></label><br />
        <span asp-validation-for="Date"></span><br />
        
        <label>Project: <input asp-for="ProjectName" /></label> <br />
        <span asp-validation-for="ProjectName"></span><br />
        
        <label>Description of Tasks: <input asp-for="TaskDescription" /></label><br />
        <span asp-validation-for="TaskDescription"></span><br />
        
        <label>Hours Worked: <input asp-for="HoursWorked" /></label> <br />
        <span asp-validation-for="HoursWorked"></span><br />
        
        <button type="submit">Submit</button>

    </form>

</div>